# Based on:
# https://stackoverflow.com/questions/24765930/add-swap-memory-with-ansible
# https://askubuntu.com/questions/103915/how-do-i-configure-swappiness
# https://unix.stackexchange.com/questions/23072/how-can-i-check-if-swap-is-active-from-the-command-line
---
- name: swap | Allocate swap file
  ansible.builtin.command: fallocate -l 1g /swapfile
  args:
    creates: /swapfile
  tags:
    - swap

- name: swap | Set swap file permissions
  ansible.builtin.file:
    path: /swapfile
    owner: root
    group: root
    mode: "0600"
  tags:
    - swap

- name: swap | Check swap file type
  ansible.builtin.command: file /swapfile
  register: swapfile
  changed_when: false
  tags:
    - swap

- name: swap | Make swap area if not present
  ansible.builtin.command: mkswap /swapfile
  when: swapfile.stdout.find('swap file') == -1
  tags:
    - swap

- name: swap | Write swap entry in fstab
  ansible.posix.mount:
    state: present
    src: /swapfile
    path: none
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
  tags:
    - swap

- name: swap | Mount swap if not mounted
  ansible.builtin.command: swapon /swapfile
  when: ansible_swaptotal_mb < 1
  tags:
    - swap

- name: swap | Set swappiness in /etc/sysctl.d
  ansible.builtin.copy:
    content: |
      vm.swappiness = 20
    dest: /etc/sysctl.d/60-swappiness.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Load swappiness settings
  tags:
    - swap
